# Generated by Django 5.2.6 on 2025-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('day_1', models.CharField(blank=True, max_length=1, null=True)),
                ('day_2', models.CharField(blank=True, max_length=1, null=True)),
                ('day_3', models.CharField(blank=True, max_length=1, null=True)),
                ('day_4', models.CharField(blank=True, max_length=1, null=True)),
                ('day_5', models.CharField(blank=True, max_length=1, null=True)),
                ('day_6', models.CharField(blank=True, max_length=1, null=True)),
                ('day_7', models.CharField(blank=True, max_length=1, null=True)),
                ('day_8', models.CharField(blank=True, max_length=1, null=True)),
                ('day_9', models.CharField(blank=True, max_length=1, null=True)),
                ('day_10', models.CharField(blank=True, max_length=1, null=True)),
                ('day_11', models.CharField(blank=True, max_length=1, null=True)),
                ('day_12', models.CharField(blank=True, max_length=1, null=True)),
                ('day_13', models.CharField(blank=True, max_length=1, null=True)),
                ('day_14', models.CharField(blank=True, max_length=1, null=True)),
                ('day_15', models.CharField(blank=True, max_length=1, null=True)),
                ('day_16', models.CharField(blank=True, max_length=1, null=True)),
                ('day_17', models.CharField(blank=True, max_length=1, null=True)),
                ('day_18', models.CharField(blank=True, max_length=1, null=True)),
                ('day_19', models.CharField(blank=True, max_length=1, null=True)),
                ('day_20', models.CharField(blank=True, max_length=1, null=True)),
                ('day_21', models.CharField(blank=True, max_length=1, null=True)),
                ('day_22', models.CharField(blank=True, max_length=1, null=True)),
                ('day_23', models.CharField(blank=True, max_length=1, null=True)),
                ('day_24', models.CharField(blank=True, max_length=1, null=True)),
                ('day_25', models.CharField(blank=True, max_length=1, null=True)),
                ('day_26', models.CharField(blank=True, max_length=1, null=True)),
                ('day_27', models.CharField(blank=True, max_length=1, null=True)),
                ('day_28', models.CharField(blank=True, max_length=1, null=True)),
                ('day_29', models.CharField(blank=True, max_length=1, null=True)),
                ('day_30', models.CharField(blank=True, max_length=1, null=True)),
                ('day_31', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Class', models.IntegerField(default=1)),
            ],
        ),
    ]
