# Generated by Django 5.2.6 on 2025-10-04 09:50

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.student_image_path),
        ),
    ]
