# Generated by Django 5.2.6 on 2025-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('1', models.CharField(max_length=1)),
                ('2', models.CharField(max_length=1)),
                ('3', models.CharField(max_length=1)),
                ('4', models.CharField(max_length=1)),
                ('5', models.CharField(max_length=1)),
                ('6', models.CharField(max_length=1)),
                ('7', models.CharField(max_length=1)),
                ('8', models.CharField(max_length=1)),
                ('9', models.CharField(max_length=1)),
                ('10', models.CharField(max_length=1)),
                ('11', models.CharField(max_length=1)),
                ('12', models.CharField(max_length=1)),
                ('13', models.CharField(max_length=1)),
                ('14', models.CharField(max_length=1)),
                ('15', models.CharField(max_length=1)),
                ('16', models.CharField(max_length=1)),
                ('17', models.CharField(max_length=1)),
                ('18', models.CharField(max_length=1)),
                ('19', models.CharField(max_length=1)),
                ('20', models.CharField(max_length=1)),
                ('21', models.CharField(max_length=1)),
                ('22', models.CharField(max_length=1)),
                ('23', models.CharField(max_length=1)),
                ('24', models.CharField(max_length=1)),
                ('25', models.CharField(max_length=1)),
                ('26', models.CharField(max_length=1)),
                ('27', models.CharField(max_length=1)),
                ('28', models.CharField(max_length=1)),
                ('29', models.CharField(max_length=1)),
                ('30', models.CharField(max_length=1)),
                ('31', models.CharField(max_length=1)),
            ],
        ),
    ]
