# Generated by Django 5.2.6 on 2025-09-11 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='project.schoolclass'),
        ),
    ]
