# Generated by Django 5.2.6 on 2025-09-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_schoolclass_alter_student_photo_student_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.IntegerField(default=1),
        ),
    ]
