# Generated by Django 5.2.6 on 2025-09-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_student_school_class_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
