# Generated by Django 5.2.6 on 2025-09-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_student_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
